# Generated by Django 5.1.1 on 2024-09-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='agent',
            new_name='agents',
        ),
    ]
