# Generated by Django 5.1.1 on 2024-09-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='is_vaccination',
            new_name='is_vaccinated',
        ),
    ]
