# Generated by Django 5.1.1 on 2024-10-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Vaccine Name'),
        ),
    ]
